[buf]
symbol = "ï’ "
style = "fg:#D769A1"

[c]
symbol = "î˜ "
style = "fg:#D769A1"

[conda]
symbol = "ï„Œ "
style = "fg:#D769A1"

[dart]
symbol = "î˜ "
style = "fg:#D769A1"

[directory]
read_only = " ï ½"
style = "fg:#D3869B"


[docker_context]
symbol = "ïŒˆ "
style = "fg:#D769A1"

[elixir]
symbol = "î‰µ "
style = "fg:#BCBAA0"

[elm]
symbol = "î˜¬ "
style = "fg:#BCBAA0"

[fossil_branch]
symbol = "ï˜ "
style = "fg:#A0BCA2"

[git_branch]
symbol = "ï˜ "
style = "fg:#BCBAA0"

[golang]
symbol = "î˜§ "
style = "fg:#D769A1"


[guix_shell]
symbol = "ïŒ¥ "
style = "fg:#D769A1"

[haskell]
symbol = "î· "
style = "fg:#D769A1"

[haxe]
symbol = "âŒ˜ "
style = "fg:#D769A1"

[hg_branch]
symbol = "ï˜ "
style = "fg:#A0BCA2"

[hostname]
ssh_symbol = "î¬ "
style = "fg:#DFAA520"

[git_status]
style = "fg:#BCBAA0"

[java]
symbol = "î‰– "
style = "fg:#D769A1"

[julia]
symbol = "î˜¤ "
style = "fg:#D769A1"

[lua]
symbol = "î˜  "
style = "fg:#D769A1"

[memory_usage]
symbol = "ï¡š "
style = "fg:#BCBAA0"

[meson]
symbol = "ï¨¶ "
style = "fg:#D769A1"

[nim]
symbol = "ïš¤ "
style = "fg:#D769A1"

[nix_shell]
symbol = "ïŒ“ "
style = "fg:#D769A1"

[nodejs]
symbol = "îœ˜ "
style = "fg:#D769A1"

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "

[package]
symbol = "ï£– "
style = "fg:#D769A1"

[pijul_channel]
symbol = "ğŸªº "
style = "fg:#D769A1"

[python]
symbol = "îˆµ "
style = "fg:#D769A1"

[rlang]
symbol = "ï³’ "
style = "fg:#D769A1"

[ruby]
symbol = "î‘ "
style = "fg:#D769A1"

[rust]
symbol = "î¨ "
style = "fg:#D769A1"


[scala]
symbol = "îœ· "
style = "fg:#D769A1"

[spack]
symbol = "ğŸ…¢ "
style = "fg:#D769A1"

[azure]
disabled = true
format = '[ï´ƒ $subscription]($style) '
style = "fg:#D769A1"

[terraform]
format = "via [$symbol]($style) "
symbol = "ó±¢ "
style = "fg:#D769A1"


[cmd_duration]
format = ""
style = "fg:#BCBAA0"
